# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Expand
version:      2.02
version_from: Expand.pm
installdirs:  site
requires:
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
